name: test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          path: main
          
      - name: Checkout test runner
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          repository: exercism/clojure-test-runner
          path: clojure-test-runner

      - name: setup babashka
        uses: turtlequeue/setup-babashka@v1.3.0
        with:
          babashka-version: 0.8.1
          
      - name: babashka script
        id: bb_script
        run: bb main/test.clj
          
      # Print the output of the babashka script from the
      # `bb_script` step 
      - name: Get the script output
        run: echo "${{ steps.bb_script.outputs.bb_out }}"
